---
kind: pipeline
type: docker
name: build

platform:
  arch: amd64
  os: linux

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags

  - name: release
    image: golang
    environment:
      GITHUB_TOKEN:
        from_secret: GH_TOKEN
    commands:
      - curl -sL https://git.io/goreleaser | bash
    when:
      event:
        - tag
