before:
  hooks:
    - go mod download
builds:
  - binary: amictl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: zip
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"