name: Run tests

on:
  push:
  pull_request:

jobs:
  lint:
    name: Check lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: reviewdog/action-staticcheck@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_on_error: true

  tests:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Prepare
        run: go mod download
      -
        name: Run tests
        run: go test ./pkg/...
      -
        name: Coverage
        run: go test -coverpkg=./pkg/... -coverprofile=coverage.out ./pkg/...
